version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: catalog_service
    ports:
      - "3306:3306"
  review-service:
    image: mysql:8
    container_name: review-service
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: review-service
    depends_on:
      - db
    ports:
      - "3307:3306"